### ISSUE TITLE
效果如何呢？

### ISSUE THREAD

**Issue by linzhk** [QipengGuo/GraphWriter-DGL#1]
我自己也跑了作者的code，感觉生成的质量不算很高。有很多重复且复制的实体不全

**Comment by QipengGuo** [comment]
是的，agenda数据集有点难，现在最新的方法就是引入预训练模型，生成质量会很高，你说的这些问题都可以解决。我自己也有尝试，确实很好，顺利的话，以后也会放代码。

**Comment by linzhk** [comment]
Investigating Pretrained Language Models for Graph-to-Text Generation
这篇paper利用一些预训练模型来做该任务的生成。效果看起来不错，有非常大的提升

**Comment by QipengGuo** [comment]
是的，我们有follow这篇

**Comment by wutaiqiang** [comment]
两位大佬好！这篇论文貌似有个问题，就是论文里说不用title效果会差很多，我跑了一下发现其实不用title效果没有那么差~

**Comment by wutaiqiang** [comment]
> Investigating Pretrained Language Models for Graph-to-Text Generation
> 这篇paper利用一些预训练模型来做该任务的生成。效果看起来不错，有非常大的提升

可惜那个作者还没开源~

**Comment by dzysunshine** [comment]
> 是的，agenda数据集有点难，现在最新的方法就是引入预训练模型，生成质量会很高，你说的这些问题都可以解决。我自己也有尝试，确实很好，顺利的话，以后也会放代码。

您好，请问您说的这个引入预训练模型的代码已经放出来了吗？

**Comment by QipengGuo** [comment]
流程快的话，可能12月下旬会放出，不过有很多其他因素。

**Comment by wonderlandais** [comment]
麻烦问一下大家都可以正常运行这个代码吗？我的会出现Cannot assign node feature "ft" on device cuda:0 to a graph on device cpu. Call DGLGraph.to() to copy the graph to the same device. 修改后会遇到rst = rst.view(feat.shape) + feat
RuntimeError: shape '[610, 500]' is invalid for input of size 1220000。请问怎么解决呀？是和版本有关系吗？

**Comment by QipengGuo** [comment]
https://github.com/dmlc/dgl/tree/master/examples/pytorch/graphwriter 版本更替太多，推荐用DGL官方repo的，会一直更新

**Comment by wonderlandais** [comment]
谢谢！
