### ISSUE TITLE
A doubt in the implement of BucketSampler.

### ISSUE THREAD

**Issue by linzhk** [QipengGuo/GraphWriter-DGL#2]
I was learning your code and here is my question about the BucketSampler:

utils.py 
`mlen = max([0]+[lens[x] for x in batch])`
maybe lens should be reinitialized by
`lens = torch.Tensor([len(x) for x in self.data_source])`
rather than 
`lens = lens[perm]`

if there is anything wrong, please point out and thank you for your help.

**Comment by QipengGuo** [comment]
You are right, it's a bug.

**Comment by QipengGuo** [comment]
Fixed
