### ISSUE TITLE
如果用到基于知识图谱的对话上

### ISSUE THREAD

**Issue by kuroko730** [QipengGuo/GraphWriter-DGL#3]
把对话中的上一句话作为title输入，知识三元组作为graph输入，作者大大觉得效果会如何呢？

**Comment by QipengGuo** [comment]
可行的，其实就是一个text encoder，一个graph encoder，加上一个text decoder

**Comment by kuroko730** [comment]
谢谢回复，
的确，把自己的数据改成agenda数据集的格式跑了几次。
结果来看Bleu效果有18-19左右，感觉Title的输入需要想办法加强一下。

还有个问题想请教一下，
这段代码里面，如果取ft2会出现tensor的shape不符合的问题，自己改成了ft则正常运行。。。不知道是什么情况
https://github.com/QipengGuo/GraphWriter-DGL/blob/11436fb1ccca5f9c5f817b1264b0f101d04a52ac/modules.py#L125
https://github.com/QipengGuo/GraphWriter-DGL/blob/11436fb1ccca5f9c5f817b1264b0f101d04a52ac/modules.py#L127

**Comment by QipengGuo** [comment]
我试了一下，shape好像没问题的
